version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

    # Minimum release age required for pnpm
    cooldown:
      default-days: 1

    allow:
      - dependency-name: "baseline-browser-mapping"
      - dependency-name: "prettier"
      - dependency-name: "workbox-cli"