version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

    allow:
      - dependency-name: "baseline-browser-mapping"
      - dependency-name: "prettier"
      - dependency-name: "workbox-cli"